apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: adnoc-demo
  description: ADNOC Demo Application
  annotations:
    github.com/project-slug: dxcorg/adnoc-demo
    backstage.io/techdocs-ref: dir:.
    
spec:
  type: website
  lifecycle: experimental
  owner: Mostafa Elkhouly
