apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: adnoc-demo
  annotations:
    github.com/project-slug: dxcorg/adnoc-demo
    backstage.io/techdocs-ref: value
spec:
  type: other
  lifecycle: unknown
  owner: guests
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives include 'googleGcs', 'awsS3', and other supported publishers. See configuration documentation for the full list.
